# Generated by Django 3.2.16 on 2022-12-14 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_genre', models.CharField(choices=[('NP', 'No Preference'), ('ACT', 'Action'), ('ADV', 'Adventure'), ('COM', 'Comedy'), ('CRI', 'Crime'), ('DRA', 'Drama'), ('FAM', 'Family'), ('FAN', 'Fantasy'), ('HOR', 'Horror'), ('MUS', 'Music'), ('ROM', 'Romance'), ('SCI', 'Sci-Fi'), ('SPT', 'Sport'), ('SUP', 'Superhero'), ('THR', 'Thriller'), ('WAR', 'War'), ('WST', 'Western')], max_length=50)),
                ('favourite_director', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
