# Generated by Django 3.2.16 on 2022-12-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite_genre',
            field=models.CharField(blank=True, choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('COM', 'Comedy'), ('CRI', 'Crime'), ('DRA', 'Drama'), ('FAM', 'Family'), ('FAN', 'Fantasy'), ('HOR', 'Horror'), ('MUS', 'Music'), ('ROM', 'Romance'), ('SCI', 'Sci-Fi'), ('SPT', 'Sport'), ('SUP', 'Superhero'), ('THR', 'Thriller'), ('WAR', 'War'), ('WST', 'Western')], default='', max_length=50),
        ),
    ]
