# Generated by Django 3.2.16 on 2022-12-16 20:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder_image', max_length=255, verbose_name='movie image'),
        ),
    ]
