# Generated by Django 3.2.16 on 2022-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221216_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
