# Generated by Django 3.2.16 on 2022-12-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(blank=True, choices=[('U', 'U'), ('PG', 'PG'), ('12', '12'), ('12A', '12A'), ('15', '15'), ('18', '18')], default='', max_length=50),
        ),
    ]
