# Generated by Django 3.2.16 on 2022-12-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Music', 'Music'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Sport', 'Sport'), ('Superhero', 'Superhero'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
